# Generated by Django 4.2.8 on 2024-01-11 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='images',
            new_name='image',
        ),
    ]
